title: Front-end-developer-interview-questions
description: A list of helpful front-end related questions you can use to interview potential candidates, test yourself or completely ignore.
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
